# Generated by Django 4.2 on 2024-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productpicture',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='productpicture',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category_pics/'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='image',
            field=models.ImageField(null=True, upload_to='product_pics/'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
