# Generated by Django 4.2 on 2024-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
