# Generated by Django 4.2 on 2024-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_product_main_image_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='website.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
