# Generated by Django 4.2 on 2024-09-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_product_categories_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='website.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Percentage'), (1, 'Fixed Amount')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
