# Generated by Django 4.2 on 2024-09-19 19:59

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_product_categories_alter_product_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='product/main_images'),
        ),
    ]
