# Generated by Django 4.2 on 2024-09-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
