# Generated by Django 4.2 on 2024-08-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendoremployee',
            unique_together=set(),
        ),
    ]
