# Generated by Django 4.2 on 2024-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Owner'), (0, 'Customer'), (2, 'Manager'), (3, 'Operator')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
