# Generated by Django 4.2 on 2024-08-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
