# Generated by Django 4.2 on 2024-09-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Sending', 'Sending'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
    ]
